<?php

namespace AppBundle\Repository;

/**
 * AdquisicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdquisicionRepository extends \Doctrine\ORM\EntityRepository
{
}
