<?php

namespace AppBundle\Repository;

/**
 * CodigoUNSPSCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodigoUNSPSCRepository extends \Doctrine\ORM\EntityRepository
{
}
